# Generated by Django 6.0.1 on 2026-03-04 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_exerciseschedule_nutrationplane'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrationplane',
            name='relation',
        ),
        migrations.DeleteModel(
            name='ExerciseSchedule',
        ),
        migrations.DeleteModel(
            name='NutrationPlane',
        ),
    ]
