# Generated by Django 6.0.1 on 2026-03-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_nutrationplane_relation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('meta_description', models.TextField()),
                ('keywords', models.CharField(max_length=255)),
                ('canonical_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
